name: Build Guaranteed Optimized Searcher

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install customtkinter pillow pyinstaller

    - name: Download UPX for Compression
      run: |
        invoke-webrequest https://github.com/upx/upx/releases/download/v4.2.2/upx-4.2.2-win64.zip -OutFile upx.zip
        expand-archive upx.zip -DestinationPath .

    - name: Build EXE with PyInstaller & UPX
      run: |
        pyinstaller --noconsole --onefile --collect-all customtkinter --icon=my_icon.ico --upx-dir=upx-4.2.2-win64 test2.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Turbo-Searcher-Final
        path: dist/test2.exe
