name: Build Windows EXE

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install customtkinter Pillow pyinstaller

    - name: Build EXE with Icon
      run: |
        pyinstaller --noconfirm --onefile --windowed --icon="my_icon.ico" --name "BatchRenamerPro" main.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Windows-Executable
        path: dist/BatchRenamerPro.exe
