name: Build Windows EXE
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install customtkinter pyinstaller
        
    - name: Build EXE
      run: |
        # التعديل هنا لاسم ملفك الجديد test2.py
        pyinstaller --noconsole --onefile --icon=my_icon.ico --collect-all customtkinter test2.py
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Tamer-Searcher-App-V2
        path: dist/*.exe
